/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini.invoiceservice;

public class HelloWorld {
	public static void main(String[] args) {
		System.out.println("Hello World!!");
	}
}
